export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  supabaseUrl: process.env.SUPABASE_URL ?? "",
  supabaseServiceRoleKey: process.env.SUPABASE_SERVICE_ROLE_KEY ?? "",
  votingTable: process.env.VOTATION_TABLE ?? "cdbnc",
  votingStart: process.env.VOTATION_START ?? "2026-01-18T19:00:00-03:00",
  votingEnd: process.env.VOTATION_END ?? "2026-08-25T19:00:00-03:00",
  votesPerCaptcha: Number(process.env.VOTOS_POR_CAPTCHA ?? "10"),
  challengeTtlMs: Number(process.env.CAPTCHA_CHALLENGE_TTL_MS ?? "180000"),
  rateLimitWindowMs: Number(process.env.VOTING_RATE_LIMIT_WINDOW_MS ?? "60000"),
  rateLimitMax: Number(process.env.VOTING_RATE_LIMIT_MAX ?? "20"),
};
